<a href="https://colab.research.google.com/github/wasim-kilani/data_science_w1/blob/main/Tut3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#1
array=np.array([[10,2],[30,49]])
print(array)

[[10  2]
 [30 49]]


In [5]:
#2
random_3_4=np.random.rand(3,4)
print(random_3_4)

[[3.43625565e-02 4.84637812e-01 5.88095145e-01 3.57851352e-01]
 [8.99171961e-02 5.09905090e-01 3.81555574e-04 5.79705823e-02]
 [7.69550551e-02 6.75807214e-01 1.38385192e-02 4.75348736e-01]]


In [7]:
#3
zeroz=np.zeros((3,4))
print(zeroz)
onez=np.ones((3,3))
print(onez)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#4
array63=np.random.randint(0,10, size = (6,3))
print(array63)
arrayT=array63.T
print(arrayT)

[[5 7 9]
 [2 2 7]
 [6 3 2]
 [0 7 2]
 [2 2 3]
 [0 3 8]]
[[5 2 6 0 2 0]
 [7 2 3 7 2 3]
 [9 7 2 2 3 8]]


In [15]:
#5
n = 2
p = 1
m = 4
A = np.random.rand(n , p)
print(A)
B = np.random.rand(p , m)
print(B)
print("                                      ")
DOT = np.dot(A,B)
print(DOT)

[[0.40576449]
 [0.13409187]]
[[0.10398167 0.91149947 0.5891201  0.90331977]]
                                      
[[0.04219207 0.36985412 0.23904402 0.36653509]
 [0.0139431  0.12222467 0.07899622 0.12112784]]
